### PR TITLE
Anticonf

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by jimhester** [comment]
Ok this is now setup to using our standard configure scripts to find the dependencies. On macOS without homebrew (like on CRAN's machines) the dependencies are temporarily installed the package is compiled with static linking and the dependencies are removed, so the precompiled binaries will still work.

**Comment by jeroen** [comment]
I missed this but this is a bad idea. Packages deliberately download the autobrew bootstrap script on-the-fly because I continuously tweak them to keep up with upstream changes in R and homebrew.

Currently I am preparing all autobrew scripts for R 4.0 and I noticed `ragg` is not working anymore. 

There is no benefit of including the autobrew script in the package, because without internet access it won't work anyway.

**Comment by thomasp85** [comment]
Can you make a PR to update it to current best practice?

**Comment by jimhester** [comment]
Did you read my commit message in e266d75, I explained why we couldn't download the script like normal. If you have a way to use the same brew instance for all the package dependencies needed in the upstream script than we can happily use that instead.

**Comment by jeroen** [comment]
I don't understand what you mean by that commit message. Why do you need to use the same brew directory for all packages? I deliberately prevent that because the Mac builder installs many packages concurrently, and you don't want to have two packages run brew commands simultanously.

**Comment by jimhester** [comment]
It has been a while, but I think the problem was the separate system dependencies needed for ragg were being installed in completely separate homebrew installs, which didn't work. But yes separate R packages should use their own homebrew installs.

**Comment by jeroen** [comment]
OK i'll look into it and send a PR later today

**Pull request merged**
